### ISSUE TITLE
What's the differences between this project and Chimera Linux?

### ISSUE THREAD

**Issue by Curculigo** [iglunix/iglunix#123]
This project is completely new to me. I know about it when browsing muon's repository. I have never use Chimera Linux, either. I know about it from distrowatch. From README.md, I know you are using toybox+busybox instead of BSD userland like Chimera. This is the only thing I know about your project now. Btw, may I ask you why it's toybox+busybox? Is it a typo? Are you really mean toybox or busybox? Because using both sounds wrong to me.

**Comment by Ella-0** [comment]
Chimara and Iglunix have different goals. Chimera aims to be Linux with a BSD userland. Iglunix aims to be a minimal self-hosting system without any GNU software.
We use toybox because it's good enough. We use busybox aswell to fill in the gaps where toybox hasn't implemented something.
