### ISSUE TITLE
upgrading to python 3.11 is broken

### ISSUE THREAD

**Issue by aheirman** [iglunix/iglunix#21]

**Comment by Ella-0** [comment]
there are some pains with python. most notably i always uninstall my previous python before compiling a new python. that helps deal with some ensure pip bugs.

**Comment by aheirman** [comment]
it was something with the host triple. In my case both `$TRIPLE` and `$HOST_TRIPLE` are empty

**Comment by aheirman** [comment]
and I don't have pip

**Comment by Ella-0** [comment]
> it was something with the host triple. In my case both `$TRIPLE` and `$HOST_TRIPLE` are empty

How old is your `iglupkg`?

**Comment by aheirman** [comment]
a couple hours

**Comment by aheirman** [comment]
try to upgrade it to python 3.11.1, it it works for you then it's odd

**Comment by Ella-0** [comment]
is definitely working now
