### ISSUE TITLE
Some links in build scripts don't exist

### ISSUE THREAD

**Issue by iamthenoname** [iglunix/iglunix#3]
The link for the build script in "linux/linux" isn't available in the aports anymore (https://git.alpinelinux.org/aports/plain/testing/linux-edge)

EDIT: I also discovered that the patch file in "base/llvm" is missing too (https://reviews.llvm.org/file/data/fwstsxaybgq26x5dtdbg/PHID-FILE-pptlyffhoud7h2kme6qo/D100835.diff)

**Comment by Ella-0** [comment]
Should be fixed now
