### ISSUE TITLE
Regarding reflex

### ISSUE THREAD

**Issue by firasuke** [iglunix/iglunix#5]
Hey there,

I noticed that you've removed `flex` and that you're using `reflex` as a drop-in replacement instead.

How are you finding it so far?

Keep up the great work!

**Comment by Ella-0** [comment]
I reverted this change due to a couple reasons:
 - mesa requires more modifications to build
 - the device tree compiler doesn't play nicely with reflex

**Comment by firasuke** [comment]
I see.

Have you tried [RE-flex](https://github.com/Genivia/RE-flex)?

**Comment by Ella-0** [comment]
I'm fairly sure I have; I can't remember my reasoning behind not using it.

**Comment by aheirman** [comment]
If there are more questions you can reopen it.
