### ISSUE TITLE
Use Rust Coreutils instead of Busybox 

### ISSUE THREAD

**Issue by undesarrolladormas** [iglunix/iglunix#9]
[uutils/coreutils](https://github.com/uutils/coreutils)
Has a MIT license and the project wants to provide a cross-plataform replacement of the classic coreutils

**Comment by anoraktrend** [comment]
No. Implementing rust is a nightmare.

**Comment by Ella-0** [comment]
> [uutils/coreutils](https://github.com/uutils/coreutils) Has a MIT license and the project wants to provide a cross-plataform replacement of the classic coreutils

Why. what benefit does it have over toybox.
